version: '3'
services:
  db-mongo:
    image: mongo
    restart: always
    container_name: db-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      TZ: "Asia/Hong_Kong"
    networks:
      - outside
    volumes:
      - /time/DB:/data/db
      - /data/Dump:/data/Dump
      - ./mongod.conf:/etc/mongod.conf
    command: >
      bash -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
      echo $TZ > /etc/timezone &&
      mongod --config /etc/mongod.conf"
networks:
  outside:
    external:
      name: mongonet