services:
  db-mongo:
    image: mongo
    container_name: db-mongo
    networks:
      - mongonet
    volumes:
      - ./db-notes-mongo:/data/db
      - ./mongod.conf:/etc/mongod.conf
    command: mongod --config /etc/mongod.conf
