version: '3'
services:
  db-mongo:
    image: mongo
    restart: always
    container_name: db-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - outside
    volumes:
      - /time/DB:/data/db
      # - ./mongod.conf:/etc/mongod.conf
    # command: mongod --config /etc/mongod.conf
    command: mongod 
networks:
  outside:
    external:
      name: mongonet